import type { RobotsTxtOptions, SitemapOptions } from './sitemap-generation/types.js';

export interface NgxSeoConfig {
  siteUrl: string;
  sitemap: SitemapOptions;
  /** Generated by default. Set to `false` to omit robots.txt. */
  robots?: RobotsTxtOptions | false;
}
