import type { RobotsTxtOptions, SitemapOptions } from './sitemap-generation/types.js';
import type { SeoMetadata } from './metadata/types.js';

export interface NgxSeoConfig {
  siteUrl: string;
  sitemap: SitemapOptions;
  /** Global metadata used as the fallback for route-level SEO data. */
  metadata?: SeoMetadata;
  /** Generated by default. Set to `false` to omit robots.txt. */
  robots?: RobotsTxtOptions | false;
}
